a = int(input("Digite o valor de a:"))
b = int(input("Digite o valor de B: "))
c = int(input("Digite o valor de C: "))

print(a < b)
print(a <= b)
print(a > b)
print(a >= b)
print(a < c)
print(a <= c)
print(a > c)
print(a >= c)
print(c < b)
print(c <= b)
print(c > b)
print(c >= b)